[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/remboursement"
  to = "/.netlify/functions/remboursement"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
